### ISSUE TITLE
Will the “stream-flow” still be updated?

### ISSUE THREAD

**Issue by MrLiu92** [ScriptorBob/stream-flow#5]
I really love this plugin and would love to learn about its updated content and gain a deeper understanding of stream-flow features. I'm not sure if stream-flow will support Chinese installation and language in the future. I really hope to support Chinese in the future. It's really convenient.

**Comment by ScriptorBob** [comment]
Streamflow is still being worked on, because it is primarily a personal tool I use with Maya. 
for Chinese language support, It would require some deeper structural changes in order create a multi-lingual plugin. As of now, there are no immediate plans to implement this, but If it gets enough traction it will be implemented

**Comment by ScriptorBob** [comment]
Streamflow is still being worked on, because it is primarily a personal tool I use with Maya.
for Chinese language support, It would require some deeper structural changes in order create a multi-lingual plugin. As of now, there are no immediate plans to implement this, but If it gets enough traction it will be implemented
